/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.itecbrazil.serviceftpcliente.view;

import br.itecbrazil.serviceftpcliente.enums.EnumTipoArquivo;
import br.itecbrazil.serviceftpcliente.model.Arquivo;
import br.itecbrazil.serviceftpcliente.model.ArquivoDao;
import java.io.FileNotFoundException;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author willian
 */
public class PanelAuditoriaEnvio extends javax.swing.JPanel {
private List<Arquivo> listaDeArquivosEnviados;
    /**
     * Creates new form PanelAuditoriaEnvio
     */
    public PanelAuditoriaEnvio() {
        setListaDeArquivosEnviados();
        initComponents();
        buildView();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setBackground(new java.awt.Color(255, 255, 255));

        jTable1.setModel(new TableModelArquivosTransmitidos
            (getListaDeArquivosEnviados()));
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 660, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(101, 101, 101)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 440, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    public List<Arquivo> getListaDeArquivosEnviados() {
        return listaDeArquivosEnviados;
    }
    
    private void setListaDeArquivosEnviados() {
        ArquivoDao arquivoDao = new ArquivoDao();
        try {
            listaDeArquivosEnviados = arquivoDao.getArquivos(EnumTipoArquivo.Envio.getTipoDoArquivo());
            if(listaDeArquivosEnviados == null)
                listaDeArquivosEnviados = new ArrayList<Arquivo>();
            
        } catch (FileNotFoundException ex) {
            Logger.getLogger(PanelAuditoriaEnvio.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void buildView() {
        
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
