/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.itecbrazil.serviceftpcliente.view;

import java.awt.Color;

/**
 *
 * @author willian
 */
public class PanelAuditoria extends javax.swing.JPanel {

    /**
     * Creates new form Auditoria
     */
    public PanelAuditoria() {
        initComponents();
        criarTabs();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel_titulo = new javax.swing.JLabel();
        jTabbedPanel_abas = new javax.swing.JTabbedPane();

        setBackground(new java.awt.Color(0, 126, 244));
        setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0)));

        jLabel_titulo.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel_titulo.setForeground(java.awt.Color.white);
        jLabel_titulo.setText("Auditoria de envio e retorno");

        jTabbedPanel_abas.setBackground(new java.awt.Color(0, 126, 244));
        jTabbedPanel_abas.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jTabbedPanel_abas.setOpaque(true);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel_titulo)
                        .addGap(0, 435, Short.MAX_VALUE))
                    .addComponent(jTabbedPanel_abas))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel_titulo, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPanel_abas, javax.swing.GroupLayout.DEFAULT_SIZE, 475, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel_titulo;
    private javax.swing.JTabbedPane jTabbedPanel_abas;
    // End of variables declaration//GEN-END:variables

    private void criarTabs() {
        PanelAuditoriaEnvio panelEnvio = new PanelAuditoriaEnvio();
        PanelAuditoriaRetorno panelRetorno = new PanelAuditoriaRetorno();
        jTabbedPanel_abas.addTab("Arquivos de envio", null, panelEnvio, "Auditar arquivos enviados");
        jTabbedPanel_abas.addTab("Arquivos de retorno", null, panelRetorno, "Auditar arquivos retornados");
        jTabbedPanel_abas.setBackgroundAt(0, new Color(204,204,204));
        jTabbedPanel_abas.setBackgroundAt(1, new Color(204,204,204));
    }

}
