/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.itecbrazil.serviceftpcliente.view;

import br.itecbrazil.serviceftpcliente.controller.ControllerPanelConfigServidoresFTPs;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author itec-desenv-willian
 */
public class PanelConfigServidoresFTPs extends javax.swing.JPanel {

    private DefaultTableModel modeloDaTabelaDeConfigFTP;
    private ControllerPanelConfigServidoresFTPs controller;

    /**
     * Creates new form PanelConfigServidoresFTPs
     */
    public PanelConfigServidoresFTPs() {
        modeloDaTabelaDeConfigFTP = new DefaultTableModel() {
            @Override
            public boolean isCellEditable(int rowIndex, int mColIndex) {
                return false;
            }
        };
        initComponents();
        controller = new ControllerPanelConfigServidoresFTPs(this);
    }

    public JTable getjTableConfigFTP() {
        return jTableConfigFTP;
    }

    public ControllerPanelConfigServidoresFTPs getController() {
        return controller;
    }

    public DefaultTableModel getModeloDaTabelaDeConfigFTP() {
        return modeloDaTabelaDeConfigFTP;
    }

    public void popularTabelaDeConfiguracoesFTPs() {
        getController().popularTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPaneConfigFTP = new javax.swing.JScrollPane();
        jTableConfigFTP = new javax.swing.JTable();
        jLabelTitulo = new javax.swing.JLabel();
        jButtonAdcionarConfig = new javax.swing.JButton();
        jButtonLimpar = new javax.swing.JButton();

        setBackground(new java.awt.Color(159, 195, 251));
        setAutoscrolls(true);
        setMaximumSize(new java.awt.Dimension(680, 225));
        setMinimumSize(new java.awt.Dimension(680, 225));
        setName("JPanelConfigFTP"); // NOI18N
        setPreferredSize(new java.awt.Dimension(680, 225));

        jTableConfigFTP.setModel(modeloDaTabelaDeConfigFTP);
        jTableConfigFTP.setMaximumSize(new java.awt.Dimension(598, 100));
        jTableConfigFTP.setMinimumSize(new java.awt.Dimension(598, 100));
        jTableConfigFTP.setName("jTableConfigFTP"); // NOI18N
        jTableConfigFTP.setRowHeight(25);
        jTableConfigFTP.setRowSelectionAllowed(false);
        jTableConfigFTP.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableConfigFTPMouseClicked(evt);
            }
        });
        jScrollPaneConfigFTP.setViewportView(jTableConfigFTP);

        jLabelTitulo.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabelTitulo.setText("Dados servidor ativo");

        jButtonAdcionarConfig.setText("Adicionar Novas Configurações");
        jButtonAdcionarConfig.setName("jButtonAdcionarConfig"); // NOI18N
        jButtonAdcionarConfig.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAdcionarConfigActionPerformed(evt);
            }
        });

        jButtonLimpar.setText("Limpar Configurações");
        jButtonLimpar.setName("jButtonLimpar"); // NOI18N
        jButtonLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLimparActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPaneConfigFTP, javax.swing.GroupLayout.DEFAULT_SIZE, 660, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabelTitulo)
                        .addGap(26, 26, 26)
                        .addComponent(jButtonAdcionarConfig)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonLimpar)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, 26, Short.MAX_VALUE)
                    .addComponent(jButtonAdcionarConfig)
                    .addComponent(jButtonLimpar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPaneConfigFTP, javax.swing.GroupLayout.DEFAULT_SIZE, 151, Short.MAX_VALUE)
                .addGap(25, 25, 25))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jTableConfigFTPMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableConfigFTPMouseClicked
        if (getjTableConfigFTP().columnAtPoint(evt.getPoint()) == 4) {
            Object cnpjDaLinhaSelecionada = getjTableConfigFTP().getValueAt(getjTableConfigFTP().getSelectedRow(), 1);
            int linhaSelecionada = getjTableConfigFTP().getSelectedRow();
            getController().dispararAcaoDoController(getjTableConfigFTP().columnAtPoint(evt.getPoint()), linhaSelecionada, cnpjDaLinhaSelecionada);
        }
    }//GEN-LAST:event_jTableConfigFTPMouseClicked

    private void jButtonAdcionarConfigActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAdcionarConfigActionPerformed
        getController().adicionarConfiguracoesDeFTP();
    }//GEN-LAST:event_jButtonAdcionarConfigActionPerformed

    private void jButtonLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLimparActionPerformed
        getController().limparConfiguracoes();
    }//GEN-LAST:event_jButtonLimparActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAdcionarConfig;
    private javax.swing.JButton jButtonLimpar;
    private javax.swing.JLabel jLabelTitulo;
    private javax.swing.JScrollPane jScrollPaneConfigFTP;
    private javax.swing.JTable jTableConfigFTP;
    // End of variables declaration//GEN-END:variables
}
