
package br.itecbrazil.serviceftpcliente.view;

import br.itecbrazil.serviceftpcliente.controller.ControllerCadastroConfiguracaoFTP;
import java.awt.event.ActionEvent;
import java.awt.event.KeyEvent;
import javax.swing.AbstractAction;
import javax.swing.ActionMap;
import javax.swing.ImageIcon;
import javax.swing.InputMap;
import javax.swing.JComponent;
import javax.swing.JOptionPane;
import static javax.swing.JOptionPane.WARNING_MESSAGE;
import javax.swing.JTextField;
import javax.swing.KeyStroke;

/**
 *
 * @author itec-desenv-willian
 */
public class ViewCadastroDeConfiguracaoFTP extends javax.swing.JDialog {
 ControllerCadastroConfiguracaoFTP controllerCadastroConfiguracaoFTP;
    /**
     * A return status code - returned if Cancel button has been pressed
     */
    public static final int RET_CANCEL = 0;
    /**
     * A return status code - returned if OK button has been pressed
     */
    public static final int RET_OK = 1;

    /**
     * Creates new form ViewCadastroDeConfiguracaoFTP
     * @param parent
     * @param modal
     */
    public ViewCadastroDeConfiguracaoFTP(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        controllerCadastroConfiguracaoFTP =  new ControllerCadastroConfiguracaoFTP(this);
        initComponents();
        ImageIcon img = new ImageIcon(getClass().getResource("/itecBrazil.png"));
        setIconImage(img.getImage());
        // Close the dialog when Esc is pressed
        String cancelName = "cancel";
        InputMap inputMap = getRootPane().getInputMap(JComponent.WHEN_ANCESTOR_OF_FOCUSED_COMPONENT);
        inputMap.put(KeyStroke.getKeyStroke(KeyEvent.VK_ESCAPE, 0), cancelName);
        ActionMap actionMap = getRootPane().getActionMap();
        actionMap.put(cancelName, new AbstractAction() {
            @Override
            public void actionPerformed(ActionEvent e) {
                doClose(RET_CANCEL);
            }
        });
    }

    /**
     * @return the return status of this dialog - one of RET_OK or RET_CANCEL
     */
    public int getReturnStatus() {
        return returnStatus;
    }

    public JTextField getjTextFieldDiretorioEnvio() {
        return jTextFieldDiretorioEnvio;
    }

    public JTextField getjTextFieldDiretorioRetorno() {
        return jTextFieldDiretorioRetorno;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        okButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();
        jLabelDiretorioRetorno = new javax.swing.JLabel();
        jLabelDiretorioEnvio = new javax.swing.JLabel();
        jTextFieldDiretorioRetorno = new javax.swing.JTextField();
        jTextFieldDiretorioEnvio = new javax.swing.JTextField();
        jLabelImportaXML = new javax.swing.JLabel();
        jButtonImportarXML = new javax.swing.JButton();
        jLabelPathArquivo = new javax.swing.JLabel();
        jButtonPesqDiretorioRetorno = new javax.swing.JButton();
        jButtonPesquisaDirEnvio = new javax.swing.JButton();

        setTitle("Cadastro de Configuração do FTP");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                closeDialog(evt);
            }
        });

        okButton.setText("OK");
        okButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okButtonActionPerformed(evt);
            }
        });

        cancelButton.setText("Cancel");
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });

        jLabelDiretorioRetorno.setText("Diretório de Retorno:");

        jLabelDiretorioEnvio.setText("Diretório de Envio:");

        jTextFieldDiretorioRetorno.setToolTipText("caminho completo do diretório de retorno");
        jTextFieldDiretorioRetorno.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        jTextFieldDiretorioRetorno.setEnabled(false);

        jTextFieldDiretorioEnvio.setToolTipText("caminho completo do diretório de envio");
        jTextFieldDiretorioEnvio.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        jTextFieldDiretorioEnvio.setEnabled(false);

        jLabelImportaXML.setText("Importar XML do Servidor:");

        jButtonImportarXML.setLabel("Importar");
        jButtonImportarXML.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonImportarXMLActionPerformed(evt);
            }
        });

        jLabelPathArquivo.setText(" ");

        jButtonPesqDiretorioRetorno.setText("...");
        jButtonPesqDiretorioRetorno.setToolTipText("Pesquisar diretório de retorno");
        jButtonPesqDiretorioRetorno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPesqDiretorioRetornoActionPerformed(evt);
            }
        });

        jButtonPesquisaDirEnvio.setText("...");
        jButtonPesquisaDirEnvio.setToolTipText("Pesquisar diretório de envio");
        jButtonPesquisaDirEnvio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPesquisaDirEnvioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(okButton, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cancelButton))
                    .addComponent(jLabelPathArquivo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabelDiretorioRetorno, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelDiretorioEnvio)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabelImportaXML, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonImportarXML))
                            .addComponent(jTextFieldDiretorioRetorno, javax.swing.GroupLayout.DEFAULT_SIZE, 330, Short.MAX_VALUE)
                            .addComponent(jTextFieldDiretorioEnvio))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButtonPesqDiretorioRetorno, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonPesquisaDirEnvio, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {cancelButton, okButton});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelDiretorioRetorno)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldDiretorioRetorno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonPesqDiretorioRetorno, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addComponent(jLabelDiretorioEnvio)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldDiretorioEnvio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonPesquisaDirEnvio, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelImportaXML)
                    .addComponent(jButtonImportarXML))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelPathArquivo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 90, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cancelButton)
                    .addComponent(okButton))
                .addContainerGap())
        );

        getRootPane().setDefaultButton(okButton);
        jLabelPathArquivo.getAccessibleContext().setAccessibleName("");
        jLabelPathArquivo.getAccessibleContext().setAccessibleDescription("");

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void okButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okButtonActionPerformed

        if(controllerCadastroConfiguracaoFTP.validarFormulario(jTextFieldDiretorioEnvio.getText(),jTextFieldDiretorioRetorno.getText())){
            if(controllerCadastroConfiguracaoFTP.getArquivoXMLDeImportacao().length() == 0){
                JOptionPane.showMessageDialog(this, "INFO: O arquivo de configuração não possui conteudo", "ALERT", WARNING_MESSAGE);
            }else{
                controllerCadastroConfiguracaoFTP.criarConfiguracaoFTP(jTextFieldDiretorioEnvio.getText(),jTextFieldDiretorioRetorno.getText());
            }
        }
    }//GEN-LAST:event_okButtonActionPerformed

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        doClose(RET_CANCEL);
    }//GEN-LAST:event_cancelButtonActionPerformed

    /**
     * Closes the dialog
     */
    private void closeDialog(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_closeDialog
        doClose(RET_CANCEL);
    }//GEN-LAST:event_closeDialog

    private void jButtonImportarXMLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonImportarXMLActionPerformed

        controllerCadastroConfiguracaoFTP.carregarXML();
        if(controllerCadastroConfiguracaoFTP.getArquivoXMLDeImportacao()!=null)
        jLabelPathArquivo.setText(controllerCadastroConfiguracaoFTP.getArquivoXMLDeImportacao().getAbsolutePath());
    }//GEN-LAST:event_jButtonImportarXMLActionPerformed

    private void jButtonPesqDiretorioRetornoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPesqDiretorioRetornoActionPerformed
        controllerCadastroConfiguracaoFTP.carregarDiretorio(getjTextFieldDiretorioRetorno());
    }//GEN-LAST:event_jButtonPesqDiretorioRetornoActionPerformed

    private void jButtonPesquisaDirEnvioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPesquisaDirEnvioActionPerformed
        controllerCadastroConfiguracaoFTP.carregarDiretorio(getjTextFieldDiretorioEnvio());
    }//GEN-LAST:event_jButtonPesquisaDirEnvioActionPerformed

    private void doClose(int retStatus) {
        returnStatus = retStatus;
        setVisible(false);
        dispose(); 
    }

  
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelButton;
    private javax.swing.JButton jButtonImportarXML;
    private javax.swing.JButton jButtonPesqDiretorioRetorno;
    private javax.swing.JButton jButtonPesquisaDirEnvio;
    private javax.swing.JLabel jLabelDiretorioEnvio;
    private javax.swing.JLabel jLabelDiretorioRetorno;
    private javax.swing.JLabel jLabelImportaXML;
    private javax.swing.JLabel jLabelPathArquivo;
    private javax.swing.JTextField jTextFieldDiretorioEnvio;
    private javax.swing.JTextField jTextFieldDiretorioRetorno;
    private javax.swing.JButton okButton;
    // End of variables declaration//GEN-END:variables

    private int returnStatus = RET_CANCEL;
}
