/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.itecbrazil.serviceftpcliente.view;

import br.itecbrazil.serviceftpcliente.controller.ControllerViewHome;
import br.itecbrazil.serviceftpcliente.model.ScheduleEngine;
import javax.swing.ImageIcon;

/**
 *
 * @author itec-desenv-willian
 */
public class ViewHome extends javax.swing.JFrame {

    ControllerViewHome controller;

    /**
     * Creates new form ViewHome
     */
    public ViewHome() {
        controller = new ControllerViewHome(this);
        initComponents();
        ImageIcon img = new ImageIcon(getClass().getResource("/itecBrazil.png"));
        setIconImage(img.getImage());
        panelConfigLocalDiretorios.preencherPathDiretorios();
        panelConfigServidoresFTP.popularTabelaDeConfiguracoesFTPs();
        ScheduleEngine.prepararEIniciarScheduler();
        controller.rodarServicoEmBackGround();

    }

    public ControllerViewHome getController() {
        return controller;
    }

    public PanelConfigLocalDiretorios getPanelConfig() {
        return this.panelConfigLocalDiretorios;
    }

    public PanelConfigServidoresFTPs getPanelConfigServidoresFTP() {
        return panelConfigServidoresFTP;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelConfigServidoresFTP = new br.itecbrazil.serviceftpcliente.view.PanelConfigServidoresFTPs();
        panelDashBoardEnvioRetorno = new br.itecbrazil.serviceftpcliente.view.PanelDashBoardEnvioRetorno();
        jLabelRodape = new javax.swing.JLabel();
        panelConfigLocalDiretorios = new br.itecbrazil.serviceftpcliente.view.PanelConfigLocalDiretorios();

        setTitle("HOME SERVICE FTP CLIENT");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setMinimumSize(new java.awt.Dimension(712, 630));

        jLabelRodape.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabelRodape.setText("Copyright ©  ItecBrazil");
        jLabelRodape.setToolTipText("");
        jLabelRodape.setName("jLabelRodape"); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelConfigServidoresFTP, javax.swing.GroupLayout.DEFAULT_SIZE, 692, Short.MAX_VALUE)
                    .addComponent(panelDashBoardEnvioRetorno, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabelRodape)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(panelConfigLocalDiretorios, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addComponent(panelConfigLocalDiretorios, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelConfigServidoresFTP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelDashBoardEnvioRetorno, javax.swing.GroupLayout.DEFAULT_SIZE, 235, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelRodape, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel*/
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                ViewHome viewHome = new ViewHome();
                viewHome.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabelRodape;
    private br.itecbrazil.serviceftpcliente.view.PanelConfigLocalDiretorios panelConfigLocalDiretorios;
    private br.itecbrazil.serviceftpcliente.view.PanelConfigServidoresFTPs panelConfigServidoresFTP;
    private br.itecbrazil.serviceftpcliente.view.PanelDashBoardEnvioRetorno panelDashBoardEnvioRetorno;
    // End of variables declaration//GEN-END:variables
}
