/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.itecbrazil.serviceftpcliente.view;

import br.itecbrazil.serviceftpcliente.controller.ControllerViewHome;
import br.itecbrazil.serviceftpcliente.model.ScheduleEngine;
import javax.swing.ImageIcon;
import javax.swing.JFrame;

/**
 *
 * @author itec-desenv-willian
 */
public class ViewHome extends javax.swing.JFrame {

    ControllerViewHome controller;
    private PanelConfigLocalDiretorios panelConfigLocalDiretorios;
    private PanelConfigServidoresFTPs panelConfigServidoresFTPs;

    /**
     * Creates new form ViewHome
     */
    public ViewHome() {
        controller = new ControllerViewHome(this);
        initComponents();
        panelConfigLocalDiretorios = new PanelConfigLocalDiretorios();
        panelConfigServidoresFTPs = new PanelConfigServidoresFTPs();
        ScheduleEngine.prepararEIniciarScheduler();
        controller.rodarServicoEmBackGround();
    }

    public ControllerViewHome getController() {
        return controller;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelRodape = new javax.swing.JLabel();
        jPanel_container = new javax.swing.JPanel();
        jMenuBar_barraDeMenu = new javax.swing.JMenuBar();
        jMenu_configuracao = new javax.swing.JMenu();
        jMenuItem_diretorio = new javax.swing.JMenuItem();
        jMenuItem_servidor = new javax.swing.JMenuItem();
        jMenu_logs = new javax.swing.JMenu();

        setTitle("HOME SERVICE FTP CLIENT");
        setBackground(new java.awt.Color(255, 255, 255));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setExtendedState(JFrame.MAXIMIZED_BOTH);
        setIconImage(new ImageIcon(getClass().getResource("/two_war_2.png")).getImage());
        setMinimumSize(new java.awt.Dimension(712, 630));

        jLabelRodape.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabelRodape.setText("Copyright © 2WAR");
        jLabelRodape.setToolTipText("");
        jLabelRodape.setName("jLabelRodape"); // NOI18N

        jPanel_container.setBackground(new java.awt.Color(255, 255, 255));
        jPanel_container.setLayout(new java.awt.CardLayout());

        jMenuBar_barraDeMenu.setBackground(new java.awt.Color(255, 255, 255));

        jMenu_configuracao.setText("Configuração");
        jMenu_configuracao.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N

        jMenuItem_diretorio.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jMenuItem_diretorio.setText("Diretórios");
        jMenuItem_diretorio.setToolTipText("Diretório local de envio e recebimento de arquivos");
        jMenuItem_diretorio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_diretorioActionPerformed(evt);
            }
        });
        jMenu_configuracao.add(jMenuItem_diretorio);

        jMenuItem_servidor.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jMenuItem_servidor.setText("Servidor");
        jMenuItem_servidor.setToolTipText("Configurando as informações do servidor e de usuário");
        jMenuItem_servidor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_servidorActionPerformed(evt);
            }
        });
        jMenu_configuracao.add(jMenuItem_servidor);

        jMenuBar_barraDeMenu.add(jMenu_configuracao);

        jMenu_logs.setText("Logs");
        jMenu_logs.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jMenuBar_barraDeMenu.add(jMenu_logs);

        setJMenuBar(jMenuBar_barraDeMenu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel_container, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabelRodape)
                        .addGap(0, 587, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel_container, javax.swing.GroupLayout.DEFAULT_SIZE, 566, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelRodape, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem_diretorioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_diretorioActionPerformed
        jPanel_container.removeAll();
        jPanel_container.repaint();
        jPanel_container.revalidate();
        
        jPanel_container.add(panelConfigLocalDiretorios);
        jPanel_container.repaint();
        jPanel_container.revalidate();
    }//GEN-LAST:event_jMenuItem_diretorioActionPerformed

    private void jMenuItem_servidorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_servidorActionPerformed
        jPanel_container.removeAll();
        jPanel_container.repaint();
        jPanel_container.revalidate();
        
        jPanel_container.add(panelConfigServidoresFTPs);
        jPanel_container.repaint();
        jPanel_container.revalidate();
    }//GEN-LAST:event_jMenuItem_servidorActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel*/
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                ViewHome viewHome = new ViewHome();
                viewHome.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabelRodape;
    private javax.swing.JMenuBar jMenuBar_barraDeMenu;
    private javax.swing.JMenuItem jMenuItem_diretorio;
    private javax.swing.JMenuItem jMenuItem_servidor;
    private javax.swing.JMenu jMenu_configuracao;
    private javax.swing.JMenu jMenu_logs;
    private javax.swing.JPanel jPanel_container;
    // End of variables declaration//GEN-END:variables
}
